
AWSTemplateFormatVersion: 2010-09-09
Description: This component contains all ressources needed to Implement Windows VSS Backup.

Parameters:
  Stage:
    Description: Stage of the application
    Type: String
  ServiceName:
    Description: The name of the application to roll out
    Type: String
  EC2Ids:
    Description: 'The instance IDs of up to ten EC2 instances that you want to patch with VSS enabled.'
    Type: 'List<AWS::EC2::Instance::Id>'
  EC2Roles:
    Description: 'The EC2 Roles of the Instances to grant VSS permission'
    Type: 'List<String>'

Resources:
###########################################################################################################
############# ONLY VALID FOR WINDOWS BACKUPS                                           ####################
############# DELETE THIS FILE IF YOU USE LINUX EC2 IMAGES                             ####################
###########################################################################################################
### VolumeShadowCopy setup ###
  VssComponentSSMAssociation:
    Type: AWS::SSM::Association
    Properties: 
      Name: "AWS-ConfigureAWSPackage"
      OutputLocation:
        S3Location:
          OutputS3BucketName: !Ref SsmAssociationOutputBucket
          OutputS3KeyPrefix: "SsmAssoc"
      Parameters: 
        name:
          - "AwsVssComponents"
        action:
          - "Install"
        installationType:
          - "Uninstall and reinstall"
      Targets:
        - Key: InstanceIds
          Values: 
            - !Select [0, !Ref EC2Ids]

  VssComponentBackupPolicy:
    Metadata:
      cfn_nag:
        rules_to_suppress:  
          - id: W12
            reason: "The * resource on pass role is allowed since naming pattern cannot be determined at this stage."
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: "CreateVssBackups"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "ec2:CreateTags"
            Resource:
              - "arn:aws:ec2:*::snapshot/*"
              - "arn:aws:ec2:*::image/*"
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
              - "ec2:CreateSnapshot"
              - "ec2:CreateImage"
              - "ec2:DescribeImages"
            Resource: "*"
      Roles: 
        - !Select [0, !Ref EC2Roles]

### S3 related ###
  SsmAssociationOutputBucket:
    Metadata:
      cfn_nag:
        rules_to_suppress:  
          - id: W35
            reason: "Cloudtrail has already handled"  
          - id: W51
            reason: "Cloudtrail has already handled"  
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${ServiceName}-vss-ssm-assoc-${Stage}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True


###########################################################################################################
############# END OF WINDOWS BACKUP                                                   #####################
###########################################################################################################