AWSTemplateFormatVersion: 2010-09-09
Description: Ec2 Patch Stack

Parameters:
  Stage:
    Description: Stage of the application
    Type: String
  ServiceName:
    Description: The name of the application to roll out
    Type: String
  OSPatchingTimeWindow:
    Description: Cron or rate expression which defines, when to auto-patch windows instances
    Type: String
  OSPatchingTimeZone:
    Description: Timezone for the OSPatching
    Type: String
  PatchTag:
    Description: Tag to identify relevant Ec2 instances
    Type: String
  PatchVersionName:
    Type: String
    Description: Version of Ec2 Patch Product
    Default: v0.1

Resources:
  EC2Patching:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: EC2-Patching
      ProvisionedProductName: !Sub "${ServiceName}-EC2Patching-${Stage}"
      ProvisioningArtifactName: !Ref PatchVersionName
      ProvisioningParameters:
        - Key: Timezone
          Value: !Ref OSPatchingTimeZone
        - Key: OSPatchingTimeWindow
          Value: !Ref OSPatchingTimeWindow
        - Key: PatchTag
          Value: !Ref PatchTag