AWSTemplateFormatVersion: 2010-09-09
Description: Application Load Balancer S3 Bucket
Parameters:
  ServiceName:
    Type: "String"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Metadata:
      cfn_nag:
        rules_to_suppress:  
          - id: W35
            reason: "Done via Cloudtrail"    
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256

  S3ForceSSLBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:PutObject"
            Effect: Allow
            Principal:
              #AWS: "arn:aws:iam::127311923021:root" # us-east-1
              AWS: "arn:aws:iam::054676820928:root" # eu-central-1
              ## Replace by the Account required for your region
              ## https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/${ServiceName}/AWSLogs/${AWS::AccountId}/*"
          - Action: "s3:PutObject"
            Effect: Allow
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/${ServiceName}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: 'bucket-owner-full-control'
          - Action: "s3:GetBucketAcl"
            Effect: Allow
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}"
          - Action: "s3:*"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - !GetAtt S3Bucket.Arn
              - !Sub '${S3Bucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'
        Version: "2012-10-17"

Outputs:
  BucketName:
    Value: !Ref S3Bucket
 